In [1]:
import tensorflow as tf
print(tf.__version__)

C:\Users\saisr\AppData\Roaming\Python\Python312\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.30.0 at tensorflow/core/framework/attr_value.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\saisr\AppData\Roaming\Python\Python312\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.30.0 at tensorflow/core/framework/tensor.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\saisr\AppData\Roaming\Python\Python312\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.30.0 at tensorflow/core/framework/resource_handle.proto. Please 

2.20.0


In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1796, 9330, 1623, 6656],
 [1796, 9330, 1623, 291],
 [1796, 9344, 1623, 1328],
 [6975, 8173, 8829, 5619, 7255],
 [6975, 8173, 8829, 5619, 1568],
 [196, 1796, 4270, 1623, 9873],
 [8995, 8003, 4474, 5619]]

In [12]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [13]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1796 9330 1623 6656]
 [   0    0    0    0 1796 9330 1623  291]
 [   0    0    0    0 1796 9344 1623 1328]
 [   0    0    0 6975 8173 8829 5619 7255]
 [   0    0    0 6975 8173 8829 5619 1568]
 [   0    0    0  196 1796 4270 1623 9873]
 [   0    0    0    0 8995 8003 4474 5619]]


In [14]:
## feature representation
dim=10

In [25]:
model=Sequential()
model.add(Embedding(input_dim=voc_size,output_dim=dim, input_length=sent_length))
model.compile('adam','mse')

c:\Users\saisr\OneDrive\Desktop\GenAI\GenAI-Learnings\Simple_RNN\venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [26]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [31]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step


array([[[-0.04514572, -0.0092077 , -0.01195101,  0.02352799,
         -0.00388934, -0.02045826,  0.01459343,  0.00525055,
          0.01128485, -0.03892943],
        [-0.04514572, -0.0092077 , -0.01195101,  0.02352799,
         -0.00388934, -0.02045826,  0.01459343,  0.00525055,
          0.01128485, -0.03892943],
        [-0.04514572, -0.0092077 , -0.01195101,  0.02352799,
         -0.00388934, -0.02045826,  0.01459343,  0.00525055,
          0.01128485, -0.03892943],
        [-0.04514572, -0.0092077 , -0.01195101,  0.02352799,
         -0.00388934, -0.02045826,  0.01459343,  0.00525055,
          0.01128485, -0.03892943],
        [ 0.00604614, -0.01150697, -0.04001684,  0.00679644,
         -0.03153297,  0.03423281,  0.01192602, -0.00834994,
          0.036528  , -0.04109488],
        [ 0.02501685,  0.01041901,  0.01530392,  0.01085556,
          0.0075667 , -0.04660734,  0.01740935, -0.04035642,
         -0.018065  ,  0.04886797],
        [ 0.02811999, -0.02603792, -0.03503456,  0.0

In [32]:
embedded_docs[0]

array([   0,    0,    0,    0, 1796, 9330, 1623, 6656], dtype=int32)

In [36]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>